name: imdb_flutter
description: "IMDB in Bloc"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0

  # Architecture
  flutter_bloc: ^8.1.5

  # Dependency Injection
  get_it: ^7.7.0
  injectable: ^2.4.2

  # Navigation
  go_router: ^14.1.3

  # Networking
  http: ^1.2.1
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Localization
  imdb_localization:
    path: packages/imdb_localization

  # Utils
  logging: ^1.2.0
  equatable: ^2.0.5
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  injectable_generator: ^2.6.1
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

  thunder_analysis:
    git:
      url: https://github.com/khamidjon/thunder-analysis
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
